### ISSUE TITLE
Improvement 1: Formatear el nombre de un usuario.

### ISSUE THREAD

**Issue by fclopezjurado** [fclopezjurado/IWVG.SwC.fclopezjurado#1]
Improvement asignado a @ecastel6
Request para la implementación de Improvement 1: Formatear el nombre de un usuario.

URL a la descripción de la mejora: https://github.com/fclopezjurado/IWVG.SwC.fclopezjurado/wiki/Improvements#improvement-1-formatear-el-nombre-de-un-usuario

Se ha generado la rama Improvement#1 en el repositorio, para la elaboración de la mejora.

Las clases de test ya se encuentran listas para la mejora. Puede que el proyecto genere un error en estas clases de pruebas. Tras la finalización de la mejora, el error desaparece.

**Comment by ecastel6** [comment]
Hola @fclopezjurado 
He subido el método diff que pides a Improvement#1
He probado el método llamandole desde otra clase y funciona bien. El test parece que no tira. 
Dime si quieres que fusione y cierre el ticket. 
Salu2 @ecastel6

**Comment by fclopezjurado** [comment]
Ok, antes de fusionar, le echo un ojo esta tarde y te cuento ;-)

Un saludo!

**Comment by fclopezjurado** [comment]
El test no funciona, porque el método debe tener la cabecera _public Point diff(Point point) {}_

La función toma como referencia la coordenada del objecto y resta en cada eje, con respecto a los valores que recibe la coordenada como parámetro.

Voy a intentar explicarlo más, con una secuencia de código:

`Point point = new Point(2,3);`
`point.diff(new Point(3, 5));`
`System.out.println(point.getX()); -----> -1`

Cuando lo tengas avísame ;-)

**Comment by ecastel6** [comment]
Hola @fclopezjurado 
En efecto yo he implementado la función que recibe dos objetos Point y los resta devolviendo otro objeto Point. Si prefieres que pase el primer punto por el contructor ok. 

Otra cosa, acabo de ver que has cambiado el enunciado de la feature ¿¿¿???
Tu dirás que hago, termino el diff como pedías o lo que pone ahora

Salu2

**Comment by fclopezjurado** [comment]
Perdona por este cambio de última hora, pero es que el enunciado dice que es necesario realizar tres mejoras sobre la clase _Fraction_ y al final he tenido que modificar este ticket, perdona de verdad :-(

Culpa totalmente mía.

Deja que organice la rama y todo el tema y en unos minutillos te lo dejo todo listo ;-)

**Comment by ecastel6** [comment]
Ya está subido el nuevo método diff ahora pasa los test. Si quieres fusiono y cierro ticket. 
Salu2

**Comment by fclopezjurado** [comment]
Perdona de nuevo, de corazón, por haber cambiado la tarea :-(

Te acabo de actualizar la rama improvement#1, con el test correspondiente a la mejora.

El commit de referencia tras la modificación es c2700cd3a44fe591912abaa7ba3b66133f4d0462

Recuerdo que el encabezado de la función debe ser _public String includePointsInName() {}_

Muchas gracias y perdona por las molestias :-(

Un saludo!

Fran

**Comment by ecastel6** [comment]
Buenas @fclopezjurado 
Ya tienes hecho el método y subido a la rama, el test no pasa porque le faltaría un punto al final de la cadena con la que comparas. Creo que debería ser 

> assertEquals("F.r.a.n.", user.includePointsInName());

Ya me dirás si fusiono y cierro. Como ves tienes hechos los tres métodos que me has pedido. 
Salu2

**Comment by fclopezjurado** [comment]
Siento molestar un poco, pero según la Wiki, toca ajustar el método para que pase la prueba.

Simplemente, es necesario controlar que el índice que utilizas en el bucle, tome el mismo valor que la longitud de la cadena.

En ese caso, no debes añadir el punto tras la última letra.

Lo incluyo en pseudocódigo, para facilitarte la tarea:

`if (indice == nombre.longitud) nombreConPuntos += letra
`else nombreConPuntos += letra + "."`

Si sigues teniendo alguna duda, lo resolvemos por aquí ;-)

Un saludo!

Fran

**Comment by ecastel6** [comment]
Saludos @fclopezjurado 
Ya está modificado el método, ahora no devuelve el punto final, aunque me ha parecido más limpio añadir simplemente un         return (NamewithDots.substring(0, NamewithDots.length()-1));

Dime si fusiono y cierro ya.
Salu2

**Comment by fclopezjurado** [comment]
Buenas noches!

Felicidades y buen trabajo! ;-) funciona genial.

Cuando quieras, puedes hacer el merge con development y cerramos el ticket.

Un saludo!

Fran

**Comment by ecastel6** [comment]
Merge hecho. He tenido que resolver un conflicto pero parece que ha quedado bien. 
Cierra cuando quieras. 
Salu2

**Comment by fclopezjurado** [comment]
Todo OK.

Buen trabajo! Ticket cerrado.

Un saludo!

Fran
