### ISSUE TITLE
Improvement 3: Suma de un número entero a una fracción.

### ISSUE THREAD

**Issue by fclopezjurado** [fclopezjurado/IWVG.SwC.fclopezjurado#3]
Improvement asignado a @jmolinma 

Request para la implementación de Improvement Improvement 3: Suma de un número entero a una fracción.

URL a la descripción de la mejora: https://github.com/fclopezjurado/IWVG.SwC.fclopezjurado/wiki/Improvements#improvement-3-suma-de-un-n%C3%BAmero-entero-a-una-fracci%C3%B3n

Se ha generado la rama Improvement#3 en el repositorio, para la elaboración de la mejora.

Las clases de test ya se encuentran listas para la mejora. Puede que el proyecto genere un error en estas clases de pruebas. Tras la finalización de la mejora, el error desaparece.

**Comment by cabalito** [comment]
Buenas tardes,
Los cambios han sido realizados, si detectas algún problema házmelo saber.
Un saludo.

**Comment by fclopezjurado** [comment]
Funciona genial!

Buen trabajo @jmolinma ;-)

Cierro ticket.

Un saludo!

Fran
