### ISSUE TITLE
Improvement 4: Producto entre un número y la inversa de una fracción.

### ISSUE THREAD

**Issue by fclopezjurado** [fclopezjurado/IWVG.SwC.fclopezjurado#4]
Improvement asignado a @jmolinma

Request para la implementación de Improvement 4: Producto entre un número y la inversa de una fracción.

URL a la descripción de la mejora: https://github.com/fclopezjurado/IWVG.SwC.fclopezjurado/wiki/Improvements#improvement-4-producto-entre-un-n%C3%BAmero-y-la-inversa-de-una-fracci%C3%B3n

Se ha generado la rama Improvement#4 en el repositorio, para la elaboración de la mejora.

Las clases de test ya se encuentran listas para la mejora. Puede que el proyecto genere un error en estas clases de pruebas. Tras la finalización de la mejora, el error desaparece.

**Comment by cabalito** [comment]
Buenas tardes,
He realizado y subido los cambios. Al subir ambas ramas, se ha producido un par de conflictos que he solucionado, pero no está de más que le eches un ojo para corroborar que los cambios son correctos.
Un saludo.

**Comment by fclopezjurado** [comment]
Acabo de ver la ejecución de las pruebas, tras el merge en development.

Funciona genial ;-)

Felicidades por el trabajo y por la rapidez en su realización ;-)

Cierro ticket.

Un saludo!

Fran
