### ISSUE TITLE
Improvement 5: División de fracciones.

### ISSUE THREAD

**Issue by fclopezjurado** [fclopezjurado/IWVG.SwC.fclopezjurado#5]
Improvement asignado a @TamaraJDz 

Request para la implementación de Improvement 5: División de fracciones.

URL a la descripción de la mejora: https://github.com/fclopezjurado/IWVG.SwC.fclopezjurado/wiki/Improvements#improvement-5-divisi%C3%B3n-de-fracciones

Se ha generado la rama Improvement#5 en el repositorio, para la elaboración de la mejora.

Las clases de test ya se encuentran listas para la mejora. Puede que el proyecto genere un error en estas clases de pruebas. Tras la finalización de la mejora, el error desaparece.

**Comment by TamaraJDz** [comment]
Hola @fclopezjurado 
veo que ninguna de las tareas que tengo asignada es sobre la clase Fraction, no sé si recuerdas, pero tienes que asignar a cada programador una tarea a elegir entre las clases User, Point y DecimalCollection y otra obligatoriamente de la clase Fraction.
Por ahora voy a realizar la tarea de las coordenadas que es la primera y esta debes cambiarmela por una tarea sobre la clase Fraction.

**Comment by TamaraJDz** [comment]
Por otro lado, si no entendí mal, tu simplemente creas las ramas master y develop, las ramas nuestras de las features las creamos nosotros y no se suben al repositorio, simplemente hacemos el merge con develop y hacemos push desde develop.

**Comment by fclopezjurado** [comment]
Cierto respecto a las mejoras de las clase Fraction.

Deben ser tres mejoras en esta clase y cada desarrollador debe realizar una.

Esta tarde modifico la wiki y los restantes tickets ;-)

Un saludo

**Comment by fclopezjurado** [comment]
Respecto a la gestión de ramas, en la documentación se especifica que queda en manos del arquitecto.

Motivos por los que he creado cada rama en remoto:
- Facilitaros la vida, incluyendo la prueba en cada rama, dado que quedan pocos días para la entrega.
- Quiero que quede una mejor constancia en remoto, de todo lo que se ha hecho.

Para más dudas al respecto, consultar https://github.com/fclopezjurado/IWVG.SwC.fclopezjurado/wiki#est%C3%A1ndares-de-trabajo

**Comment by fclopezjurado** [comment]
Mientras tanto, no hay problema en que subas el improvement #2 , siempre que haya pasado todas las pruebas previamente.

**Comment by fclopezjurado** [comment]
Problema solucionado.

Siento de verdad haber tenido que modificar el enunciado de la mejora.

Ha sido culpa mía por las prisas y no revisar a tope el enunciado.

He realizado un commit sobre la rama improvement#5 con el test correspondiente.
El commit de referencia es 95ef7cac5306c8e578b60a2f44db935d27fa472d

Recuerdo que el encabezado del método debe ser si o si _public void div(Fraction fraction) {}_

Un saludo y perdona por las molestias ;-)

**Comment by TamaraJDz** [comment]
Perdona, no lo había leído, ahora mismo lo hago.

**Comment by fclopezjurado** [comment]
@TamaraJDz  No es por ser pesado, pero recuerdo por **tercera vez**, que si en la Wiki pone que el método debe tener la cabecera _public void div(Fraction fraction) {}_, **para algo está la Wiki**.

De nuevo, **por tercera vez**, menciono que si se ha creado una rama en remoto, para que realices la mejora, teniendo en cuenta que también está especificado en la wiki en https://github.com/fclopezjurado/IWVG.SwC.fclopezjurado/wiki#est%C3%A1ndares-de-trabajo , sigo sin entender por qué no has utilizado esta rama.

La mejora está perfecta, has hecho un gran trabajo, pero debería estar realizada sobre la rama #improvement5. Si ves que te apetece, modifica este aspecto y si no haz lo que quieras.

Lo que no se puede quedar, es el tipo de dato que retorna el método. Debe quedar tal y como se especifica en la Wiki.

Un saludo.

**Comment by TamaraJDz** [comment]
Hola @fclopezjurado : No te preocupes, no eres pesado. A ver, el flujo normal de git es que el desarrollador se cree su propia rama en local y desarrolle sobre ella, y eso es precisamente lo que he hecho -no es nada normal que el arquitecto cree la rama para que el desarrollador haga su trabajo en ella-. De otra forma habría tropecientas ramas en remoto. Además, una vez hecho el merge la rama no debe existir más ¿qué interés tiene esa redundancia de tener por un lado el código con su historial en la rama y por otro tenerlo en la rama develop sobre la que se hizo merge?

Por otro lado, la cabecera del método ya está cambiada. Me parecía raro que quisieras que el parámetro fuera de entrada/salida, por eso lo hice de la otra manera.

Un saludo.

**Comment by fclopezjurado** [comment]
Buenas noches @TamaraJDz .

Tienes razón al comentar, que existirían excesivas ramas en remoto en este caso.

La principal razón por la que lo hice, era incluir los test para cada mejora y mantener cada una al margen, pero lo mismo no ha sido una buena decisión :-S.

Una última cosa. Tras el cambio has dejado un **warning** en la clase _Fraction_, justo en el método de la mejora. 

Elimina la línea con las variables locales, haz el merge y cierra el ticket sin problema ;-)

Buen trabajo, muchas gracias por todo y un saludo!

Fran

**Comment by TamaraJDz** [comment]
Ya está arreglado el warning y subido, perdona por el despiste.
Cierro el ticket.
