### ISSUE TITLE
Improvement 6: Multiplicar cada elemento una colección de número decimales, por un número.

### ISSUE THREAD

**Issue by fclopezjurado** [fclopezjurado/IWVG.SwC.fclopezjurado#6]
Improvement asignado a @ecastel6 

Request para la implementación de Improvement 6: Multiplicar cada elemento una colección de número decimales, por un número.

URL a la descripción de la mejora: https://github.com/fclopezjurado/IWVG.SwC.fclopezjurado/wiki/Improvements#improvement-6-multiplicar-cada-elemento-una-colecci%C3%B3n-de-n%C3%BAmero-decimales-por-un-n%C3%BAmero

Se ha generado la rama Improvement#6 en el repositorio, para la elaboración de la mejora.

Las clases de test ya se encuentran listas para la mejora. Puede que el proyecto genere un error en estas clases de pruebas. Tras la finalización de la mejora, el error desaparece.

**Comment by ecastel6** [comment]
Buenas @fclopezjurado 
Terminado Improvement 6 subido a su rama. Pasa los test, dime si fusiono y cierro. 

Salu2

**Comment by fclopezjurado** [comment]
Funciona de cine @ecastel6 

Buen trabajo ;-)

Haz merge sobre development y cerramos ticket!

**Comment by ecastel6** [comment]
Buenas @fclopezjurado 
Hecho el merge con develop. Cierro el ticket. Ya me cuentas sobre las otras mejoras. 
Salu2
@ecastel6
